use p4g4;
GO
CREATE SCHEMA CONFERENCIAS;
GO

CREATE TABLE CONFERENCIAS.INSTITUICAO (
	nome		VARCHAR(30),
	endereco	VARCHAR(30),
	PRIMARY KEY(nome)
);


CREATE TABLE CONFERENCIAS.AUTOR(
	email		VARCHAR(30),
	nome		VARCHAR(30) NOT NULL,
	nome_inst	VARCHAR(30) NOT NULL,
	PRIMARY KEY(email),
	FOREIGN KEY(nome_inst) REFERENCES CONFERENCIAS.INSTITUICAO(nome)
);

CREATE TABLE CONFERENCIAS.ESTUDANTE(
	email			VARCHAR(30),
	nome			VARCHAR(30) NOT NULL,
	morada			VARCHAR(30),
	data			DATE,
	nome_inst		VARCHAR(30) NOT NULL,
	comprovativo	VARCHAR(30) NOT NULL,
	PRIMARY KEY(email),
	FOREIGN KEY(nome_inst) REFERENCES CONFERENCIAS.INSTITUICAO(nome)
);

CREATE TABLE CONFERENCIAS.NAO_ESTUDANTE(
	email			VARCHAR(30),
	nome			VARCHAR(30) NOT NULL,
	morada			VARCHAR(30),
	data			DATE,
	nome_inst		VARCHAR(30) NOT NULL,
	ref				VARCHAR(30) NOT NULL,
	PRIMARY KEY(email),
	FOREIGN KEY(nome_inst) REFERENCES CONFERENCIAS.INSTITUICAO(nome)
);

CREATE TABLE CONFERENCIAS.ARTIGO(
	n_registo		INT,
	titulo			VARCHAR(30),
	PRIMARY KEY(n_registo),
	UNIQUE(titulo)
);